### PR TITLE
github: correct repo name for GH action

### PR DESCRIPTION
**Pull request by evgenykor**

### CODE REVIEW

**Comment by evgenykor** [comment]
@guycipher look at it it is green now!

**Comment by guycipher** [comment]
Legend status @evgenykor 👑

**Comment by guycipher** [comment]
I look forward to seeing how everything turns out.  The API is finalized there may be one new public method coming `tidesdb_start_partial_merge` but that's going onto 0.6.0.  Other than that the entire API is indeed finalized.  So going downwards from https://github.com/tidesdb/tidesdb#:~:text=(e)%3B%0A%7D-,Transactions,-You%20can%20perform it's transactions, cursor/iterator, and the manual compaction method.  Really cool setup @evgenykor !

**Comment by evgenykor** [comment]
@guycipher we should use part of this GH workflow for tidesdb repo itself - basically copypaste

**Comment by guycipher** [comment]
We should eventually for sure.   Currently I'd have to think about how that would look like.  Currently with the C library its making sure all tests pass within test directory and there are flags etc that have to be set and unset etc depending on the kind of PR going into what version.  Keep it up @evgenykor .

**Comment by evgenykor** [comment]
Well even this partial setup/action how I build tidesDB now it waay beter than no CI at all as it is now

**Comment by evgenykor** [comment]
in other words you could always improve it in later steps/commits

**Comment by guycipher** [comment]
That's true.  As stated there are some cmake configurations I need to look at how they can work alongside the actions.  Currently yeah it's pretty manual, its not too bad though and I agree this is probably gonna change as more and more people contribute to the library.

**Pull request merged**
